import { Quote } from '../types/quote';

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'quote-1',
    vendor: {
      name: 'ABC Motors',
      location: 'Indiranagar, Bengaluru',
      phone: '+91 98450 12345',
    },
    category: 'Car Service',
    currency: 'INR',
    totalAmount: 24850,
    attentionCount: 3,
    date: '2 days ago',
    itemsCount: 8,
    notes: '40,000 km Periodic Maintenance & Brake Inspection',
    lineItems: [
      {
        id: 'li-1',
        name: 'Engine Oil Replacement (Synthetic 0W-20)',
        quantity: 1,
        unitPrice: 3800,
        totalPrice: 3800,
        attention: {
          id: 'att-1',
          level: 'clear',
          title: 'Standard Pricing',
          description: 'Matches OEM manufacturer recommended volume and synthetic grade pricing.',
        },
      },
      {
        id: 'li-2',
        name: 'Engine Decarbonization Flush',
        quantity: 1,
        unitPrice: 4200,
        totalPrice: 4200,
        attention: {
          id: 'att-2',
          level: 'review',
          title: 'Unnecessary Add-on',
          description: 'Decarbonization is rarely necessary at 40,000 km unless specific rough idling occurs.',
          suggestedQuestion: 'Is this required per the manufacturer service manual schedule, or is it an optional shop recommendation?',
        },
      },
      {
        id: 'li-3',
        name: 'Front Brake Pads & Rotor Polish',
        quantity: 1,
        unitPrice: 6500,
        totalPrice: 6500,
        attention: {
          id: 'att-3',
          level: 'ask',
          title: 'Check Remaining Pad Thickness',
          description: 'Pads are often replaced prematurely. Verify if thickness is below 3mm.',
          suggestedQuestion: 'What is the current measured pad thickness in millimeters?',
        },
      },
      {
        id: 'li-4',
        name: 'AC Disinfection & Ozone Sanitization',
        quantity: 1,
        unitPrice: 2400,
        totalPrice: 2400,
        attention: {
          id: 'att-4',
          level: 'ask',
          title: 'High Markup',
          description: 'Standard spray treatment costs ₹500–₹800 in open market.',
          suggestedQuestion: 'Can this item be waived if cabin filter is already replaced?',
        },
      },
    ],
  },
  {
    id: 'quote-2',
    vendor: {
      name: 'Cool Air Services',
      location: 'Koramangala, Bengaluru',
      phone: '+91 99001 56789',
    },
    category: 'AC Repair',
    currency: 'INR',
    totalAmount: 6200,
    attentionCount: 1,
    date: '5 days ago',
    itemsCount: 4,
    notes: 'Split AC Deep Cleaning & Gas Top-up',
    lineItems: [
      {
        id: 'li-201',
        name: 'Jet Pump Foam Wash Service',
        quantity: 2,
        unitPrice: 1100,
        totalPrice: 2200,
        attention: {
          id: 'att-201',
          level: 'clear',
          title: 'Competitive Market Rate',
          description: 'Standard market rate for dual unit deep foam service is ₹1,000–₹1,200 per unit.',
        },
      },
      {
        id: 'li-202',
        name: 'R32 Refrigerant Gas Charge',
        quantity: 1,
        unitPrice: 3200,
        totalPrice: 3200,
        attention: {
          id: 'att-202',
          level: 'ask',
          title: 'Verify Leak Test First',
          description: 'Refrigerant is in a closed loop. If gas is low, a leak check and brazing fix must be confirmed first.',
          suggestedQuestion: 'Was a nitrogen pressure test performed to identify the leak point before refilling?',
        },
      },
      {
        id: 'li-203',
        name: 'Capacitor Replacement (45uF)',
        quantity: 1,
        unitPrice: 800,
        totalPrice: 800,
        attention: {
          id: 'att-203',
          level: 'clear',
          title: 'Fair Pricing',
          description: 'Includes OEM specification capacitor and testing labor.',
        },
      },
    ],
  },
  {
    id: 'quote-3',
    vendor: {
      name: 'Urban Pro Electricals',
      location: 'Whitefield, Bengaluru',
      phone: '+91 98860 44556',
    },
    category: 'Electrical Works',
    currency: 'INR',
    totalAmount: 8950,
    attentionCount: 2,
    date: '1 week ago',
    itemsCount: 6,
    notes: 'Distribution Board Rewiring & MCB Upgrade',
  },
  {
    id: 'quote-4',
    vendor: {
      name: 'Apex Home Interior Repairs',
      location: 'HSR Layout, Bengaluru',
      phone: '+91 97400 33221',
    },
    category: 'Home Renovation',
    currency: 'INR',
    totalAmount: 43500,
    attentionCount: 4,
    date: '2 weeks ago',
    itemsCount: 11,
    notes: 'Balcony Waterproofing & Tile Grouting',
  },
];
